apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-store
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: trend-store
  template:
    metadata:
      labels:
        app: trend-store
    spec:
      containers:
        - name: trend-store
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}